kakao:
  api_key: 9922a156f850172c4608e54b2e89d03a
  redirect_uri: http://localhost:8080/api/member/login

spring:
  profiles:
    active: ${ext.profile}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      forU:
        hackathon: DEBUG

springdoc:
  use-fqn: true
  swagger-ui:
    tags-sorter: alpha
    path: /api-docs
  paths-to-match: /api/**
  model-and-view-allowed: true

