spring:
  profiles:
    active: ${ext.profile}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      forU:
        hackathon: DEBUG

springdoc:
  use-fqn: true
  swagger-ui:
    path: /api-docs
  paths-to-match: /api/**
  model-and-view-allowed: true

